name: youth_biomarkers_sdk
description: "Separated SDK for providing biomarkers data"
publish_to: none
version: 0.2.0
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  biosensesignal_flutter_sdk:
    git:
      url: https://github.com/aitzaz-dev/biosensesignalsdk.git
      ref: master
  permission_handler: ^11.3.1
  equatable: ^2.0.7
  flutter_inappwebview: ^6.1.5
  dio: ^5.7.0
  talker_flutter: ^4.6.0
  talker_dio_logger: ^4.6.0
  logger: ^2.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  assets:
    - assets/images/

